//tab_size=4
// Copyright 2021 nickmqb
// SPDX-License-Identifier: Apache-2.0

// Generated by ffigen 0.2.0
// Platform: Windows
// Target: 64-bit
stbi_load(filename cstring, x *int, y *int, channels_in_file *int, desired_channels int) *byte #Foreign("stbi_load")
